server {
    listen 80;
    listen [::]:80;
    server_name qt-bot.jloh02.dev www.qt-bot.jloh02.dev;
    server_tokens off;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://qt-bot.jloh02.dev$request_uri;
    }
}

server {
    listen 8443 default_server ssl;
    listen [::]:8443 ssl;
    server_name qt-bot.jloh02.dev;
    ssl_certificate /etc/letsencrypt/live/qt-bot.jloh02.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qt-bot.jloh02.dev/privkey.pem;
    location / {
        proxy_pass http://qt-bot:3000;
    }
}